name: production
description: 生产环境机器人配置模板
version: 1.0.0
createdAt: "2024-01-01T00:00:00.000Z"
author: system
config:
  name: "生产机器人"
  version: "1.0.0"
  environment: production
  adapters:
    qq:
      enabled: true
      appId: "${QQ_APP_ID}"
      token: "${QQ_TOKEN}"
    telegram:
      enabled: true
      token: "${TELEGRAM_TOKEN}"
  database:
    type: redis
    redis:
      host: "${REDIS_HOST}"
      port: 6379
      password: "${REDIS_PASSWORD}"
      db: 0
  plugins:
    directory: "./plugins"
    autoLoad: true
    hotReload: false
    whitelist:
      - "core"
      - "admin"
      - "monitoring"
  logging:
    level: info
    file:
      enabled: true
      path: "./logs/bot.log"
      maxSize: "100MB"
      maxFiles: 10
    console:
      enabled: false
  security:
    encryption:
      enabled: true
      algorithm: "aes-256-gcm"
      key: "${ENCRYPTION_KEY}"
    rateLimit:
      enabled: true
      windowMs: 60000
      maxRequests: 100
    cors:
      enabled: true
      origins: ["https://admin.example.com"]
      methods: ["GET", "POST"]
  performance:
    maxConcurrentTasks: 50
    taskTimeout: 60000
    memoryLimit: "2GB"
    cpuLimit: 90
  monitoring:
    enabled: true
    metrics:
      enabled: true
      interval: 30000
      retention: 604800000
    health:
      enabled: true
      interval: 15000
      endpoints: ["/health", "/metrics"]
    alerts:
      enabled: true
      channels: ["email", "webhook"]
      thresholds:
        memoryUsage: 85
        cpuUsage: 90
        errorRate: 5