# Bot框架主配置文件
name: "Advanced Bot Framework"
version: "1.0.0"
debug: true

adapters:
  console:
    enabled: true
    username: "Console"
    permission: "OWNER"
    prompt: "[控制台] "
    enableHistory: true
    historySize: 100
    enableColors: true
  
  qq:
    enabled: false
    uin: 0  # QQ号
    password: ""  # 密码（可选，支持扫码登录）
    platform: 5  # 登录设备类型 (1:Android手机 2:aPad 3:Android手表 4:MacOS 5:iPad)
    allowedGroups: []  # 允许的群组列表
    allowedUsers: []   # 允许的用户列表
    adminUsers: []     # 管理员用户列表
    ownerUsers: []     # 主人用户列表
    autoAcceptFriend: true      # 自动接受好友请求
    autoAcceptGroupInvite: true # 自动接受群邀请
    dataDir: "./data/qq"         # 数据目录
    logLevel: "info"             # 日志级别
  
  telegram:
    enabled: true
    token: "7529395668:AAGa5-US-bQ0CnWBs4UO0TUeuKzgt3W426A"  # Bot Token
    allowedUsers: [6812891612]  # 允许的用户ID列表
    adminUsers: [6812891612]    # 管理员用户ID列表
    ownerUsers: [6812891612]    # 主人用户ID列表
    polling:
      enabled: true   # 启用轮询模式
      interval: 1000  # 轮询间隔(毫秒)
    webhook:
      url: ""         # Webhook URL
      port: 3443      # Webhook端口

  http:
    enabled: true
    port: 5431
    host: "0.0.0.0"
    apiKey: ""        # API密钥（可选）
    allowedIPs: []    # IP白名单（可选）
    defaultPermission: "USER"  # 默认权限级别
    userPermissions: {}        # 用户权限映射
    cors:
      enabled: true
      origin: "*"
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    # OneBot集成配置
    onebot:
      enabled: true
      http:
        enabled: true
        host: "127.0.0.1"
        port: 5700
        timeout: 0
        post_timeout: 0
      ws:
        enabled: false
        host: "127.0.0.1"
        port: 6700
      ws_reverse:
        enabled: false
        universal: ""
        api: ""
        event: ""
        reconnect_interval: 3000
      access_token: ""
      secret: ""
      plugin_routes:
        enabled: true
        base_path: "/plugins"
      post_message_format: "string"
      enable_cors: true
      cors_origin: "*"
    

database:
  type: redis
  sqlite:
    path: "./data/bot.db"
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

plugins:
  directory: "./plugins"
  autoLoad: true
  hotReload: true

  plugin_routes:
    enabled: true
    base_path: "/plugins"  # 插件路由基础路径

  # 其他配置
  post_message_format: "string"  # 消息格式：string 或 array
  enable_cors: true              # 启用CORS
  cors_origin: "*"               # CORS允许的源，可以是字符串或数组

logging:
  level: info
  file: true
  console: false

# 权限配置
permissions:
  defaultLevel: 1  # 默认用户权限级别
  adminUsers: []   # 管理员用户ID列表
  ownerUsers: []   # 主人用户ID列表

# 消息处理配置
messageHandler:
  maxRetries: 3
  retryDelay: 1000
  enableRateLimit: true
  rateLimitWindow: 60000  # 1分钟
  rateLimitMax: 30        # 每分钟最多30条消息

# 异常处理配置
errorHandler:
  logErrors: true
  preventCrash: true
  maxErrorsPerMinute: 10
